PRETRAIN_DIST="1,1,1,1,1"
SFT_DIST="0,1,0,0,0"

nlprun -n 1perc-md -g 1 "python train.py --num_hidden_layers 8 --output_dir 1perc-8 --num_train_examples 1000 --num_sft_examples 50 --learning_rate 8e-5 --pretrain_dist $PRETRAIN_DIST --sft_dist $SFT_DIST"
nlprun -n 5perc-md -g 1 "python train.py --num_hidden_layers 8 --output_dir 5perc-8 --num_train_examples 1000 --num_sft_examples 250 --learning_rate 8e-5 --pretrain_dist $PRETRAIN_DIST --sft_dist $SFT_DIST"
nlprun -n 10perc-md -g 1 "python train.py --num_hidden_layers 8 --output_dir 10perc-8 --num_train_examples 1000 --num_sft_examples 500 --learning_rate 8e-5 --pretrain_dist $PRETRAIN_DIST --sft_dist $SFT_DIST"
nlprun -n 20perc-md -g 1 "python train.py --num_hidden_layers 8 --output_dir 20perc-8 --num_train_examples 1000 --num_sft_examples 1000 --learning_rate 8e-5 --pretrain_dist $PRETRAIN_DIST --sft_dist $SFT_DIST"
nlprun -n 50perc-md -g 1 "python train.py --num_hidden_layers 8 --output_dir 50perc-8 --num_train_examples 1000 --num_sft_examples 2500 --learning_rate 8e-5 --pretrain_dist $PRETRAIN_DIST --sft_dist $SFT_DIST"
nlprun -n 100perc-md -g 1 "python train.py --num_hidden_layers 8 --output_dir 100perc-8 --num_train_examples 1000 --num_sft_examples 5000 --learning_rate 8e-5 --pretrain_dist $PRETRAIN_DIST --sft_dist $SFT_DIST"
nlprun -n infperc-md -g 1 "python train.py --num_hidden_layers 8 --output_dir infperc-8 --num_train_examples 1000 --num_sft_examples 0 --pretrain_dist $SFT_DIST --learning_rate 8e-5"